version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - dream-vacation-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/dreamvacation
      - PORT=5000
    depends_on:
      - db
    networks:
      - dream-vacation-network

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=dreamvacation
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dream-vacation-network

networks:
  dream-vacation-network:
    driver: bridge

volumes:
  postgres_data:
