version: '3.8'
services:
  backend:
    image: bashtech007/dream-vacation-backend:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/dreamvacation
      - PORT=5000
    depends_on:
      - db
    restart: unless-stopped
    
  frontend:
    image: bashtech007/dream-vacation-frontend:latest
    ports:
      - "80:80"
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    depends_on:
      - backend
    restart: unless-stopped
    
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=dreamvacation
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
