name: Deploy Dream Vacation App
on:
  push:
    branches: [ main ]

env:
  FRONTEND_IMAGE: bashtech007/dream-vacation-frontend
  BACKEND_IMAGE: bashtech007/dream-vacation-backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Terraform Init
      working-directory: ./terraform-infrastructure
      run: terraform init
    
    - name: Terraform Plan
      working-directory: ./terraform-infrastructure
      run: terraform plan -var="public_key_content=${{ secrets.EC2_SSH_PUBLIC_KEY }}"
    
    - name: Terraform Apply
      working-directory: ./terraform-infrastructure
      run: terraform apply -auto-approve -var="public_key_content=${{ secrets.EC2_SSH_PUBLIC_KEY }}"
    
    - name: Get Instance IP
      working-directory: ./terraform-infrastructure
      run: |
        INSTANCE_IP=$(terraform output -raw instance_public_ip)
        echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ env.INSTANCE_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          mkdir -p ~/dream-vacation-app
          cd ~/dream-vacation-app
          sudo docker-compose down || true
          sudo docker pull ${{ env.FRONTEND_IMAGE }}:latest
          sudo docker pull ${{ env.BACKEND_IMAGE }}:latest
          cat > docker-compose.yml << 'EOF'
          version: '3.8'
          services:
            backend:
              image: bashtech007/dream-vacation-backend:latest
              ports:
                - "5000:5000"
              restart: unless-stopped
            frontend:
              image: bashtech007/dream-vacation-frontend:latest
              ports:
                - "80:3000"
              restart: unless-stopped
              depends_on:
                - backend
          EOF
          sudo docker-compose up -d